name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore CashFlowControl.Shared.sln

    - name: Build solution
      run: dotnet build CashFlowControl.Shared.sln --configuration Release

    - name: Run tests
      run: dotnet test CashFlowControl.Shared.sln --configuration Release --no-build --verbosity normal

    - name: Generate version number
      id: version
      run: echo "VERSION=$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_ENV

    - name: Update version in .csproj
      run: |
        VERSION=${{ env.VERSION }}
        for file in $(find . -name '*.csproj'); do
          sed -i "s/<Version>.*<\/Version>/<Version>$VERSION<\/Version>/" $file
        done

    - name: Pack NuGet packages
      run: dotnet pack CashFlowControl.Shared.sln --configuration Release --output ./artifacts

    - name: Publish NuGet packages
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./artifacts/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
