name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure full repository history is fetched

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'  # Adjust the .NET version as needed

      - name: Restore dependencies
        run: dotnet restore CashFlowControl.Solution.sln

      - name: Build the solution
        run: dotnet build CashFlowControl.Solution.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test CashFlowControl.Solution.sln --no-restore --verbosity normal
